// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suujjmwrisxcrkcqovbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1dWpqbXdyaXN4Y3JrY3FvdmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NDQ4MTQsImV4cCI6MjA3NjAyMDgxNH0.Kfyv91HG-koOKGXQ4dm7y-OCqfq23mOgBeougmZ_hqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});